### ISSUE TITLE
MVPリリース レビュー依頼

### ISSUE THREAD

**Issue by m-6517** [m-6517/all-ready#125]
issueを作成いたしました。
レビューをお願いいたします。

## サービス概要
サービス名：All Ready
サービスURL：[All Ready](https://all-ready.onrender.com/)

かばんの中身を投稿・共有できるサービスです。
主な機能は下記の通りです。
- かばんに必ず入れるマストアイテムを紹介
- 他のユーザーの持ち物リストを閲覧
- 行き先に応じた持ち物リストを作成

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ユーザー登録
- [x] ログイン
  - [ ] ゲストログイン
  - [ ] Googleログイン
- [x] ログアウト
- [x] 持ち物リスト（作成、編集、削除、閲覧）
  - [x] 既存のアイテムをリストに追加
  - [x] オリジナルのアイテムをリストに追加
  - [ ] アイテムの並び替え
  - [x] アイテム数の設定
  - [x] タグの追加
  - [x] 公開設定
  - [x] 画像アップロード
  - [x] 検索（キーワード、タグ）
- [x] プロフィール編集
- [ ] ページネーション
- [ ] パスワードリセット
- [ ] 独自ドメイン
- [ ] レスポンシブ対応
- [ ] Xへのシェア
- [ ] Googleアナリティクス

## READMEレビュー時から変更した機能
**作らなくなった機能**
ゲストログイン
未ログインで閲覧可能な機能を追加したため、今後も実装しない予定です。

**追加した機能**
マストアイテム（作成、編集、削除、閲覧、画像投稿）
下記の理由により追加いたしました。
 - かばんを持たない、あるいは持ち物リストを作成しないユーザーの投稿ハードルを下げるため
 - 未ログインで閲覧可能な機能を追加するため

**MVPリリース以降に実装予定の機能**
- Googleログイン
- アイテムの並び替え
- パスワードリセット
- 独自ドメイン
- レスポンシブ対応
- Xへのシェア
- Googleアナリティクス

## サービスイメージがわかるようなスクリーンショット等
**ユーザー**
アカウント作成／ログイン
<div style="display: flex; gap: 10px;">
  <img src="https://i.gyazo.com/aded10da4670c38767c2fb481edacd31.png" width="400">
  <img src="https://i.gyazo.com/81499d1e9cd023d5d08ae6262d4d2e65.png" width="400">
</div>
プロフィール編集
<img src="https://i.gyazo.com/0eb9a2887689bb77de7e1786d45efc2b.png" width="400">

**マストアイテム**
一覧／詳細
<div style="display: flex; gap: 10px;">
  <img src="https://i.gyazo.com/a4ee03bd513bd601f5a8e6855bfd6c42.png" width="400">
  <img src="https://i.gyazo.com/cdec386fbb7d03b08cec9247d1f4c9c4.png" width="400">
</div>

**みんなの持ち物**（共有された持ち物リスト）
一覧／詳細
<div style="display: flex; gap: 10px;">
  <img src="https://i.gyazo.com/c5e66564c8b69f47fc73abd35f25d3ff.png" width="400">
  <img src="https://i.gyazo.com/3c7009aa939bb03974b9006613e87554.png" width="400">
</div>

**持ち物リスト**
一覧／詳細（アイテムをクリックし準備状況を管理）
<div style="display: flex; gap: 10px;">
  <img src="https://i.gyazo.com/a4a11687cfc07c080fb40f3df6d2eb75.png" width="400">
  <img src="https://i.gyazo.com/df402bcf1867ec8ca886a9746c8943e6.png" width="400">
</div>

**メニューのモーダル**　リスト／アイテム
<div style="display: flex; gap: 10px;">
  <img src="https://i.gyazo.com/71809c5e1cadd8754d2d11b5b48c6279.png" width="400">
  <img src="https://i.gyazo.com/4bf338306c30809fed5205c37936b4f0.png" width="400">
</div>

当初よりHerokuでデプロイを行なっておりましたが、多要素認証によるログインに失敗しデプロイできなくなりました。
11月15日にメールにて問い合わせ、Herokuサポートとのやり取りが進行中です。
つきましては、RenderでデプロイしたサービスURLを提出いたします。

ご確認のほど、よろしくお願いいたします。

**Comment by TakenakaEri** [comment]
機能確認が取れました。LGTMです〜！！
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。

**Comment by m-6517** [comment]
レビューありがとうございます！
承知いたしました。本リリースに向けて引き続き励みます。
どうぞよろしくお願いいたします！
