### ISSUE TITLE
issueベースの開発 レビュー依頼

### ISSUE THREAD

**Issue by m-6517** [m-6517/all-ready#4]
issueを作成いたしました。
レビューをお願いいたします。

■Webアプリの概要
持ち物リストを作成し、かばんの中身を投稿・共有できるサービスです。
自分の持ち物を整理し、他のユーザーのかばんの中身を参考にすることで、持ち物リストをブラッシュアップできます。
このサービスを通じて、自分の持ち物を整理するだけでなく、他のユーザーと共有し合い、より良い準備をサポートする場を提供します。

- 行き先に応じた持ち物リストを作成し、必要なアイテムを忘れずに準備できます。
- 他のユーザーの持ち物リストを閲覧し、自分のリストを改善するアイデアを得ることができます。
- ユーザーが持ち物リストを作成しない場合であっても、おすすめの持ち物（1点）を気軽に投稿・閲覧することができます。

■1週間辺りの開発に向けられる時間
- 1週間あたり：30〜45時間（ストーリーポイント：15〜22）

■ProjectsのURL
[All ready 開発プロジェクト](https://github.com/users/m-6517/projects/9)

■MVPリリースまで
- [ ] 環境構築
- [ ] Herokuデプロイ
- [ ] GitHub Actions 自動デプロイ
- [ ] トップページ
- [ ] ヘッダー
- [ ] フッター
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] おすすめアイテム作成・詳細・編集・削除・閲覧機能
- [ ] 持ち物リスト作成・詳細・編集・削除・共有機能
- [ ] かばんの中身閲覧・検索・詳細・編集・削除機能
- [ ] マイページ
- [ ] フラッシュメッセージ
- [ ] フォーム入力時エラーの個別表示
- [ ] Amazon S3
- [ ] Googleログイン
- [ ] ボトムナビゲーション
- [ ] フォントの導入
- [ ] Googleアナリティクス
- [ ] ドメイン取得
- [ ] レスポンシブ対応

■MVP後
- [ ] ブックマーク（おすすめアイテム・かばんの中身）
- [ ] アバター
- [ ] パスワードリセット
- [ ] OGP（静的・動的）
- [ ] Xシェア（おすすめアイテム・かばんの中身）
- [ ] ファビコン
- [ ] タイトルの動的出力
- [ ] 持ち物の準備状況をゲージで表示
- [ ] 持ち物リスト複製
- [ ] 準備済みのアイテムを非表示
- [ ] 準備済みのアイテムをクリア
- [ ] ページネーション
- [ ] PWA
- [ ] カラーテーマの選択
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] RSpec（モデルテスト・システムテスト）

■MVPレビュー依頼予定日
予定日：2024年 11月 10日

**Comment by kenchasonakai** [comment]
LGTMです。

MVPの段階ではユーザーに使ってもらうための最小限の機能の実装のみでよいと思いますので、Emailを使ったログインをGoogleログインのような＋αの機能などはMVPリリース後に回してしまってもよいかなと思います

**Comment by m-6517** [comment]
ご確認いただきありがとうございます。
GoogleログインはMVPリリース後に実装する想定で進めてまいります。
